version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/aka0kuro/CopeGaming"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["nodejs"]

[[analyzers]]
name = "shell"